/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmaciat;

import javax.swing.JOptionPane;

/**
 *
 * @author javi_
 */
public class FarmaciaInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form FarmaciaInterfaz
     */
    
    

    public FarmaciaInterfaz() {
        initComponents();
        distribuidor.add(opD1);
        distribuidor.add(opD2);
        distribuidor.add(opD3);
        sucursal.add(check1);
        sucursal.add(check2);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distribuidor = new javax.swing.ButtonGroup();
        sucursal = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nombreMedicamento = new java.awt.TextField();
        tipoMedicamento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cantidaMedicamento = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opD1 = new javax.swing.JRadioButton();
        opD2 = new javax.swing.JRadioButton();
        opD3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        check1 = new javax.swing.JCheckBox();
        check2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farmacia JP");
        setBackground(new java.awt.Color(204, 204, 204));

        nombreMedicamento.setName(""); // NOI18N

        tipoMedicamento.setEditable(true);
        tipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));
        tipoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMedicamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del Medicamento:");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Distribuidor:");

        opD1.setText("Cofarma");
        opD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opD1ActionPerformed(evt);
            }
        });

        opD2.setText("Empsephar");

        opD3.setText("Cemefar");

        jLabel5.setText("Sucursal para el pedido:");

        check1.setText("Principal");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });

        check2.setText("Secundaria");

        jButton1.setBackground(new java.awt.Color(0, 255, 153));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Confirmar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmado(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Borrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidaMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opD3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opD2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opD1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidaMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opD1))
                .addGap(3, 3, 3)
                .addComponent(opD2)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opD3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check1)
                    .addComponent(check2))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opD1ActionPerformed

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check1ActionPerformed

    private void confirmado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmado
        // TODO add your handling code here:
        if(nombreMedicamento.getText().isEmpty()){
            errorNombreVacio();
        }else if(comprobarNombre(nombreMedicamento.getText().toString())== false){
            errorNombre();
        }else if(tipoMedicamento.getSelectedItem().equals("Seleccione:")){
            errorTipo();
        }else if(cantidaMedicamento.getText().isEmpty()){
            errorNumVacio();
        }else if((convNumero(cantidaMedicamento.getText()))== false){
            errorConvertNumero();
        }else if(esPositivo(Integer.parseInt(cantidaMedicamento.getText()))==false){
            errorCantidad();
        }else if(sucursal.getSelection()==null){
            errorSede();
        }else if(distribuidor.getSelection()==null){
            errorDistribuidor();
        }else{
            System.out.println(nombreMedicamento.getText());
            System.out.println(tipoMedicamento.getSelectedItem());
        }
        
    }//GEN-LAST:event_confirmado

    private void borrar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrar
        // TODO add your handling code here:
        distribuidor.clearSelection();
        nombreMedicamento.setText("");
        tipoMedicamento.setSelectedItem("Seleccione:");
        sucursal.clearSelection();
        cantidaMedicamento.setText("");
    }//GEN-LAST:event_borrar
    
    private void tipoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMedicamentoActionPerformed
    
    public boolean comprobarNombre(String medicamentoNombre){
        String regex = "^[a-zA-Z0-9]+$";
        return medicamentoNombre.matches(regex);
    }
    public boolean esPositivo(int cantidad){
        if(cantidad > 0){
            return true;
        }else{
            return false;
        }
    }
    public boolean convNumero(String numero){
        try {
            Integer.parseInt(numero);
            return true;
            } catch (NumberFormatException e) {
            return false;
            }
    }
    
    public void errorNombre(){
        JOptionPane.showMessageDialog(null, "El nombre no puede tener caracteres especiales.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void errorNombreVacio(){
        JOptionPane.showMessageDialog(null, "El nombre no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void errorTipo(){
        JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de medicamento.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void errorNumVacio(){
        JOptionPane.showMessageDialog(null, "La cantidad no puede estar vacia.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void errorCantidad(){
        JOptionPane.showMessageDialog(null, "La cantidad no puede ser negativa.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void errorConvertNumero(){
        JOptionPane.showMessageDialog(null, "La cantidad debe ser numerica.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void errorDistribuidor(){
        JOptionPane.showMessageDialog(null, "Debe elegir un distribuidor.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void errorSede(){
        JOptionPane.showMessageDialog(null, "Debe elegir una sucursal para enviar.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmaciaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmaciaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmaciaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmaciaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FarmaciaInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField cantidaMedicamento;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    public javax.swing.ButtonGroup distribuidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField nombreMedicamento;
    private javax.swing.JRadioButton opD1;
    private javax.swing.JRadioButton opD2;
    private javax.swing.JRadioButton opD3;
    private javax.swing.ButtonGroup sucursal;
    private javax.swing.JComboBox<String> tipoMedicamento;
    // End of variables declaration//GEN-END:variables
}
